### ISSUE TITLE
Preparing MAG tutorial resources

### ISSUE THREAD

**Issue by Galadirith** [ImperialCollegeLondon/solo8_tutorials#1]
@rlaker sorry for the delay in getting my resources up. I've pushed the data download notebook to a new branch `feat/mag-tutorial` and also cherry picked your cd1e21a commit. We can forget about the `main.ipynb` that I had committed in 7f476fc82, it was a bit of a mess and not needed now.

If your happy with it then we can work off of `feat/mag-tutorial` either branching off or commit directly, and then when everything is ready open a PR with `feat/mag-tutorial`. I'll get by metadata notebook done today.

## Tasks

- [x] Prepare new branch for future upstream merge.
- [x] Add data download notebook.
- [x] Add analysis notebook.
- [x] Add metadata notebook.
- [x] Update README after all notebooks are finalised
- [x] Add freeze of requirements

**Comment by rlaker** [comment]
Hi Ed, I just uploaded my notebook to my science branch. How do I get that into your new branch? I've not cherry picked before

**Comment by rlaker** [comment]
Think I did it...

**Comment by Galadirith** [comment]
@rlaker amazing new gifs :blush: I think I happy with our content now. I might update things a little more in a few days, but I know you'll be away (from tomorrow I think?) so I'd be happy for us to push a PR now if you're happy?

**Comment by Galadirith** [comment]
I decided not to update the download notebook (now called the `data.ipynb`) with downloading all data used in the other notebooks. I think it's fine that each notebook can download what it needs.

**Comment by rlaker** [comment]
Thanks! I think we are all good yes, the metadata section is really clear. Do we have to make it work in Binder too?

**Comment by Galadirith** [comment]
Great, thanks so much for confirming. I think our notebook do have to work in binder, is there anything your worried will not work in Binder?

**Comment by Galadirith** [comment]
Just added a freeze of my local environment packages, I forgot I had not added that to our `feat/mag-tutorial` branch.

**Comment by rlaker** [comment]
I think it will be fine, but there are lots of stuff with files that could go wrong

**Comment by rlaker** [comment]
Can you add "astrospice" to the requirements? As in install it in your environment, because it adds a few other packages.

**Comment by Galadirith** [comment]
Ah yes sorry I missed that done now in 070468a.

**Comment by Galadirith** [comment]
I just tried running with binder, it's possible there might be some issues with Python version as some of the requirements I froze needed Python >= 3.8. I think at this point no need to figure out the right dependencies. I'm guessing they will want to create one binder that has the requirements with everyone's dependencies. We don't need Python >= 3.8 so we can wait to see what they actually want to run with and I can update our dependencies once we know that. But I'll open a PR now with what we have.

Thank so much @rlaker your notebook looks awesome, I'm going to have fun exploring with that :blush:

**Comment by Galadirith** [comment]
I'll close this now in favor of https://github.com/SolarOrbiterWorkshop/solo8_tutorials/pull/2 and we can spin up some new issues if we need to track anything like updating dependencies.
